services:
  bolt-ai:
    image: ghcr.io/stackblitz-labs/bolt.diy:latest
    container_name: bolt-ai-app
    ports:
      - "3050:5173"
    environment:
      - NODE_ENV=production
      - PORT=5173
      - MOONSHOT_API_KEY=sk-8KiLOYeaGy7jpHTfDkptnQeQZSu9EmoydYoHP0A0DmO4fmgv
      - MOONSHOT_API_BASE_URL=https://api.moonshot.cn/v1
      - RUNNING_IN_DOCKER=true
      - VITE_LOG_LEVEL=info
      - DEFAULT_NUM_CTX=32768
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bolt-network

networks:
  bolt-network:
    driver: bridge
    name: bolt-isolated